files added

diff --git a/azure-pipelines/templates/quality_gates.yml b/azure-pipelines/templates/quality_gates.yml
--- a/azure-pipelines/templates/quality_gates.yml
+++ b/azure-pipelines/templates/quality_gates.yml
@@ -1,5 +1,17 @@
 steps:
-  - task: SonarCloudPublish@1
-    displayName: Publish Quality Gate Result
-    inputs:
-      pollingTimeoutSec: '120'
+  - script: |
+      echo "Checking SonarQube Quality Gate status..."
+
+      STATUS=$(curl -s -u $(SONAR_TOKEN): \
+        "$(SONAR_HOST_URL)/api/qualitygates/project_status?projectKey=django-ecommerce" \
+        | jq -r '.projectStatus.status')
+
+      echo "Quality Gate Status: $STATUS"
+
+      if [ "$STATUS" != "OK" ]; then
+        echo "Quality Gate failed"
+        exit 1
+      else
+        echo "Quality Gate passed"
+      fi
+    displayName: "Check SonarQube Quality Gate"
